# Test your FastAPI endpoints
GET http://127.0.0.1:8000/test-db
Accept: application/json

###
GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/items/1?q=false
Accept: application/json

###
POST http://127.0.0.1:8000/items
Content-Type: application/json

{
  "name": "toys",
  "price": 2000.00,
  "is_sell": true
}

###
PUT http://127.0.0.1:8000/items/1
Content-Type: application/json

{
  "name": "toys update",
  "price": 2000.00,
  "is_sell": true
}

###
DELETE http://127.0.0.1:8000/items/1
Content-Type: application/json


###

